### ISSUE TITLE
一个不是问题的问题

### ISSUE THREAD

**Issue by starock** [DanisFabric/HamburgerButton#1]
首先感谢作者分享这么好的代码。一直很想知道类似的动效如何实现的，可之前看见的都是Swift实现的，终于有OC版本了。下载下来学习一下。

我想知道 https://github.com/DanisFabric/HamburgerButton/raw/master/menu.gif 这张gif动画是用什么软件制作的？Thank you~

**Comment by DanisFabric** [comment]
这个不是我做的，但是现在一般用After Effects可以做
